---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - secrets.yaml
  - clusterinstance.yaml

configMapGenerator:
  - files:
    - extra-manifests/master-core-password.yaml
    name: extra-manifests-cm
    namespace: sno1-cluster1

generatorOptions:
  disableNameSuffixHash: true
