apiVersion: siteconfig.open-cluster-management.io/v1alpha1
kind: ClusterInstance
metadata:
  name: sno1-cluster1
  namespace: sno1-cluster1
spec:
  cpuPartitioningMode: None
  clusterName: sno1-cluster1
  clusterImageSetNameRef: img4.17.4-x86-64-appsub
  machineNetwork:
    - cidr: 10.10.200.0/24
  networkType: OVNKubernetes
  sshPublicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC/v0/EL3Vev8pArxB8ghmFem1uLytu/ohsR3IT5jZxSvnGyX3nbgoN6nIrj+hQNYzFbTERVBW5ql/0zVOvYxhFzWPRwm5fL/iXemRRKeYuFvoxU/GBfg0+mawlGOsziHt5sZ+V9KOql5tHF/YyVQAgoCb2rP+O8A0WWLEL4P3x95O8ityLucbhoFd+3REqBWMIYtm4I85P+UKmlAh3eC2v166vYEzEPQKuMbs9I0Sl45jCIXBb9yRCuoHz/ybfwC/CE5DQRzGa0waBr+BM3rW4f8fD9HyZza0Qb6H1CK1GZdSNa8u15IiKqwvQlPEr1mkEVKG5tIus54XLFXk8ILy44mF4lQkW+t0sM9yTGsrjnBp6IYnicIWLHtAIPSYC+LlrWySsNEViwPSHd0vOJkCVsjUNfS7Sca72Yua9oEAAWYuFWWZbFAGV3JH7xY2Qb9swUiJ/zDqgb6J3um6BHmkUKL5RIzYLJLyXozjGDuylEFADn8Tka7cEkCNblt9FL1U= root@kvm.awezlab.local
  nodes:
    - automatedCleaningMode: disabled
      nodeNetwork:
        config:
          dns-resolver:
            config:
              search:
                - awezlab.local
              server:
                - 10.10.200.5
          interfaces:
            - ipv4:
                dhcp: true
                enabled: true
              name: ens1s0
              state: up
              type: ethernet
          routes:
            config:
              - destination: 0.0.0.0/0
                next-hop-address: 10.10.200.1
                next-hop-interface: ens1s0
                table-id: 254
        interfaces:
          - macAddress: '00:00:00:00:00:10'
            name: ens1s0
      bmcCredentialsName:
        name: ai-bmh-secret
      ironicInspect: ''
      hostName: sno1-cluster1
      bootMode: UEFI
      role: master
      bootMACAddress: '00:00:00:00:00:10'
      templateRefs:
        - name: ai-node-templates-v1
          namespace: open-cluster-management
      cpuArchitecture: x86_64
      bmcAddress: 'redfish-virtualmedia+http://10.10.200.145:9000/redfish/v1/Systems/local/sno1-cluster1'
  baseDomain: awezlab.local
  holdInstallation: false
  templateRefs:
    - name: ai-cluster-templates-v1
      namespace: open-cluster-management
  cpuArchitecture: x86_64
  pullSecretRef:
    name: pull-secret
