---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: master-core-password
  labels:
    machineconfiguration.openshift.io/role: master
spec:
  config:
    ignition:
      version: 3.2.0
    systemd:
      units:
        - name: core-password.service
          enabled: true
          contents: |
            [Unit]
            Description=Changes core password
            [Service]
            Type=oneshot
            ExecStart=/bin/bash -c "echo core:redhat | chpasswd"
            [Install]
            WantedBy=multi-user.target
