---
- name: Create VM using kcli
  hosts: localhost
  gather_facts: no
  vars:
    vm_name: sno1-cluster1
    memory: 32768
    numcpus: 8
    disks: "[150]"
    mac_address: "00:00:00:00:00:10"
    network_name: "br0"

  tasks:
    - name: Create VM with kcli
      ansible.builtin.command: >
        kcli create vm
        -P memory={{ memory }}
        -P numcpus={{ numcpus }}
        -P disks={{ disks }}
        -P nets='[{"name": "{{ network_name }}", "mac": "{{ mac_address }}"}]'
        {{ vm_name }}
      register: kcli_output

    - name: Show kcli output
      ansible.builtin.debug:
        var: kcli_output.stdout
